apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    application.name: immich-claim0
  name: immich-claim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 100G
status: {}
